{% if item.registry is defined and '/' not in item.image %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get update \
 && apt-get install -y python3 sudo bash ca-certificates iproute2 python3-apt aptitude systemd gnupg \
 && apt-get clean

CMD ["/lib/systemd/systemd"]
